# Generated by Django 2.1 on 2018-09-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('student_id',)},
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ml.School'),
        ),
    ]
