# Generated by Django 2.1 on 2018-09-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20180911_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ml.School'),
        ),
    ]
